[package]
name = "sha256"
version = "0.1.0"
authors = ["Daniil Kosachev <johndoe@example.com>"]
edition = "2018"

[lib]
name = "sha256"
path = "src/lib.rs"

[[bin]]
name = "sha256test"
path = "src/bin.rs"

[dependencies]
